apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    io.kompose.service: admin-portal-beta
  name: admin-portal-beta
spec:
  ports:
    - name: "8081"
      port: 8081
  type: LoadBalancer
  selector:
    io.kompose.service: admin-portal-beta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: admin-portal-beta
  name: admin-portal-beta
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: admin-portal-beta
  template:
    metadata:
      labels:
        io.kompose.service: admin-portal-beta
    spec:
      restartPolicy: Always
      containers:
        - image: fintlabsacr.azurecr.io/admin-portal:build.${BUILD_NUMBER}
          name: admin-portal-beta
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8081
          env:
            - name: TZ
              value: Europe/Oslo
            - name: fint.ldap.url
              value: ldap://10.0.0.55
            - name: fint.ldap.component-base
              value: ou=components,o=fint
            - name: fint.ldap.contact-base
              value: ou=contacts,o=fint
            - name: fint.ldap.organisation-base
              value: ou=organisations,o=fint
            - name: fint.ldap.access.template-base
              value: ou=access,o=fint
            - name: fint.portal.admin.uri
              value: https://admin-beta.fintlabs.no
            - name: fint.ldap.user
              valueFrom:
                secretKeyRef:
                  name: fint-portal-user
                  key: fint.ldap.user
            - name: fint.ldap.password
              valueFrom:
                secretKeyRef:
                  name: fint-portal-user
                  key: fint.ldap.password
            - name: fint.nam.oauth.idp-hostname
              value: idp.felleskomponent.no
            - name: fint.nam.oauth.clientId
              valueFrom:
                secretKeyRef:
                  name: fint-portal-user
                  key: fint.nam.oauth.clientId
            - name: fint.nam.oauth.clientSecret
              valueFrom:
                secretKeyRef:
                  name: fint-portal-user
                  key: fint.nam.oauth.clientSecret
            - name: fint.nam.oauth.username
              valueFrom:
                secretKeyRef:
                  name: fint-portal-user
                  key: fint.nam.oauth.username
            - name: fint.nam.oauth.password
              valueFrom:
                secretKeyRef:
                  name: fint-portal-user
                  key: fint.nam.oauth.password
