version: '3'

services:
  backend:
    image: fint/adminportal
    container_name: ${DOCKER_CONTAINER}
    restart: unless-stopped
    environment:
      PARAMS: ${runParams}
      TZ: Europe/Oslo
      logging.level.root: INFO
    ports:
      - "${DOCKER_PORT}:8080"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"

