version: '3'

services:
  backend:
    image: dtr.rogfk.no/fint-beta/admin-portal
    environment:
      TZ: Europe/Oslo

    ports:
      - "9007:8081"
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

