apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    io.kompose.service: admin-portal
  name: admin-portal
spec:
  ports:
    - name: "8081"
      port: 8081
  type: LoadBalancer
  selector:
    io.kompose.service: admin-portal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: admin-portal
  name: admin-portal
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: admin-portal
  template:
    metadata:
      labels:
        io.kompose.service: admin-portal
    spec:
      restartPolicy: Always
      containers:
        - image: fintlabsacr.azurecr.io/fint-admin-portal:dummy
          name: admin-portal
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: fint-portal-user
          env:
            - name: TZ
              value: Europe/Oslo
