springfox:
 title: 'FINT Admin Portal API'
 version: '@version@'

server:
 port: 8081


fint:
  ldap:
    url: "${url}"
    user: "${user}"
    password: "${password}"
    component-base: "ou=apis,o=fint-test"
    organisation-base: "ou=organisations,o=fint-test"
    contact-base: "ou=contacts,o=fint-test"
  k8s:
    size:
      default:
        small:
          request:
            cpu: "250m"
            memory: "128Mi"
          limit:
            cpu: "500m"
            memory: "256Mi"
        medium:
          request:
            cpu: "1"
            memory: "512Mi"
          limit:
            cpu: "1"
            memory: "1Gi"
        large:
          request:
            cpu: "1"
            memory: "1Gi"
          limit:
            cpu: "2"
            memory: "2Gi"
spring:
  main:
    allow-bean-definition-overriding: true
  cache:
    type: caffeine
    cache-names: apiServices
    caffeine:
      spec: expireAfterWrite=1h

management:
  endpoint:
    prometheus:
      enabled: true
    shutdown:
      enabled: 'true'
    health:
      show-details: 'always'
  endpoints:
    web:
      exposure:
        include: '*'
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


  info:
    git:
      mode: 'full'
