springfox:
 title: 'FINT Admin Portal API'
 version: '@version@'

server:
 port: 8081

fint:
  ldap:
    url: "${url}"
    user: "${user}"
    password: "${password}"
    component-base: "ou=apis,o=fint-test"
    organisation-base: "ou=organisations,o=fint-test"
    contact-base: "ou=contacts,o=fint-test"

spring:
  cache:
    type: caffeine
    cache-names: apiServices
    caffeine:
      spec: expireAfterWrite=1h
