apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no
resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: "/spec/url/hostname"
        value: 'admin-beta.fintlabs.no'
    target:
        kind: Application
        name: fint-admin-portal-backend
  - patch: |-
      - op: replace
        path: "/spec/onePassword/itemPath"
        value: "vaults/aks-beta-vault/items/fint-portal-user-testenv"
    target:
      kind: Application
      name: fint-admin-portal-backend
