apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-admin-portal-backend
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-admin-portal-backend
    app.kubernetes.io/instance: fint-admin-portal-backend_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8080
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-admin-portal-backend:latest
  url:
    hostname: admin-beta.fintlabs.no
    basePath: /api
  ingress:
    enabled: true
    middlewares:
      - fint-admin-portal-sso