springfox:
 title: 'FINT Admin Portal API'
 version: '@version@'

server:
 port: 8081

fint:
  ldap:
    url: "${url}"
    user: "${user}"
    password: "${password}"
    component-base: "ou=felleskomponenter,o=fint"
    organisation-base: "ou=organisasjoner,o=fint"
