springfox:
 title: 'FINT Admin Portal API'
 version: '@version@'

fint:
  ldap:
    url:
    user:
    password:
    base:
    component-base: "ou=felleskomponenter,o=fint"
    organisation-base: "ou=organisasjoner,o=fint"


