name: Deployment Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build_and_push:
    uses: FINTLabs/fint-core-workflows/.github/workflows/deploy.yaml@main
    with:
      branch-name: CT-1193-deployment
